-- Baseline do modelo de dados da secção 8 da spec.
-- Regra: esta migração nunca é editada. Alterações vêm em V3+.
-- Timestamps em UTC (TIMESTAMPTZ), dinheiro em cêntimos inteiros,
-- odds em decimal, enumerados como VARCHAR + CHECK.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    username      VARCHAR(50)  NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    avatar_url    VARCHAR(500),
    global_role   VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email     UNIQUE (email),
    CONSTRAINT uq_users_username  UNIQUE (username),
    CONSTRAINT ck_users_role      CHECK (global_role IN ('USER','ADMIN')),
    CONSTRAINT ck_users_status    CHECK (status IN ('ACTIVE','SUSPENDED'))
);

CREATE TABLE communities (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id            BIGINT       NOT NULL REFERENCES users(id),
    name                VARCHAR(60)  NOT NULL,
    slug                VARCHAR(80)  NOT NULL,
    description         VARCHAR(2000),
    avatar_url          VARCHAR(500),
    banner_url          VARCHAR(500),
    price_monthly_cents INTEGER      NOT NULL DEFAULT 0,
    currency            CHAR(3)      NOT NULL DEFAULT 'EUR',
    status              VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_communities_slug   UNIQUE (slug),
    CONSTRAINT ck_communities_price  CHECK (price_monthly_cents >= 0),
    CONSTRAINT ck_communities_name   CHECK (char_length(name) BETWEEN 3 AND 60),
    CONSTRAINT ck_communities_status CHECK (status IN ('ACTIVE','SUSPENDED'))
);
CREATE INDEX ix_communities_owner  ON communities (owner_id);
CREATE INDEX ix_communities_status ON communities (status);

CREATE TABLE community_memberships (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT      NOT NULL REFERENCES communities(id),
    user_id      BIGINT      NOT NULL REFERENCES users(id),
    role         VARCHAR(20) NOT NULL,
    status       VARCHAR(20) NOT NULL,
    joined_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ,
    version      BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_membership_community_user UNIQUE (community_id, user_id),
    CONSTRAINT ck_membership_role   CHECK (role IN ('OWNER','MODERATOR','MEMBER')),
    CONSTRAINT ck_membership_status CHECK (status IN ('ACTIVE','CANCELLED','EXPIRED'))
);
CREATE INDEX ix_membership_user_status    ON community_memberships (user_id, status);
CREATE INDEX ix_membership_status_expires ON community_memberships (status, expires_at);
CREATE INDEX ix_membership_community      ON community_memberships (community_id);

CREATE TABLE leagues (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT       NOT NULL,
    name        VARCHAR(120) NOT NULL,
    country     VARCHAR(80),
    logo_url    VARCHAR(500),
    season      INTEGER      NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_leagues_provider UNIQUE (provider_id)
);

CREATE TABLE teams (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id     BIGINT       NOT NULL,
    name            VARCHAR(120) NOT NULL,
    normalized_name VARCHAR(120) NOT NULL,
    short_name      VARCHAR(60),
    country         VARCHAR(80),
    logo_url        VARCHAR(500),
    CONSTRAINT uq_teams_provider UNIQUE (provider_id)
);
CREATE INDEX ix_teams_normalized_name      ON teams (normalized_name);
CREATE INDEX ix_teams_normalized_name_trgm ON teams USING GIN (normalized_name gin_trgm_ops);

CREATE TABLE team_aliases (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id          BIGINT       NOT NULL REFERENCES teams(id),
    alias            VARCHAR(120) NOT NULL,
    normalized_alias VARCHAR(120) NOT NULL,
    community_id     BIGINT       REFERENCES communities(id),  -- NULL = alias global
    created_by       BIGINT       NOT NULL REFERENCES users(id),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- NULLS NOT DISTINCT é obrigatório: sem ele os aliases globais (community_id
    -- NULL) não seriam deduplicados, porque NULL <> NULL num índice único.
    CONSTRAINT uq_team_alias UNIQUE NULLS NOT DISTINCT (normalized_alias, community_id)
);
CREATE INDEX ix_team_aliases_team      ON team_aliases (team_id);
CREATE INDEX ix_team_aliases_trgm      ON team_aliases USING GIN (normalized_alias gin_trgm_ops);

CREATE TABLE fixtures (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id    BIGINT      NOT NULL,
    league_id      BIGINT      NOT NULL REFERENCES leagues(id),
    home_team_id   BIGINT      NOT NULL REFERENCES teams(id),
    away_team_id   BIGINT      NOT NULL REFERENCES teams(id),
    kickoff_at     TIMESTAMPTZ NOT NULL,
    status         VARCHAR(20) NOT NULL,
    home_score     INTEGER,
    away_score     INTEGER,
    last_synced_at TIMESTAMPTZ,
    CONSTRAINT uq_fixtures_provider UNIQUE (provider_id),
    CONSTRAINT ck_fixtures_status   CHECK (status IN ('SCHEDULED','LIVE','FINISHED','POSTPONED','CANCELLED')),
    CONSTRAINT ck_fixtures_teams    CHECK (home_team_id <> away_team_id)
);
CREATE INDEX ix_fixtures_kickoff        ON fixtures (kickoff_at);
CREATE INDEX ix_fixtures_status_kickoff ON fixtures (status, kickoff_at);
CREATE INDEX ix_fixtures_league         ON fixtures (league_id);
CREATE INDEX ix_fixtures_home_team      ON fixtures (home_team_id);
CREATE INDEX ix_fixtures_away_team      ON fixtures (away_team_id);

CREATE TABLE tip_imports (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id   BIGINT      NOT NULL REFERENCES communities(id),
    author_id      BIGINT      NOT NULL REFERENCES users(id),
    raw_text       TEXT        NOT NULL,
    parser_version VARCHAR(20) NOT NULL,
    status         VARCHAR(20) NOT NULL,
    line_errors    JSONB       NOT NULL DEFAULT '[]'::jsonb,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_tip_imports_status CHECK (status IN ('OK','PARTIAL','FAILED'))
);
CREATE INDEX ix_tip_imports_community ON tip_imports (community_id, created_at DESC);

CREATE TABLE tips (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT        NOT NULL REFERENCES communities(id),
    author_id    BIGINT        NOT NULL REFERENCES users(id),
    import_id    BIGINT        REFERENCES tip_imports(id),
    note         VARCHAR(500),
    stake_units  NUMERIC(4,2)  NOT NULL,
    total_odds   NUMERIC(6,3)  NOT NULL,
    bookmaker    VARCHAR(60),
    status       VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    published_at TIMESTAMPTZ,
    settled_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version      BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ck_tips_stake  CHECK (stake_units > 0),
    CONSTRAINT ck_tips_odds   CHECK (total_odds >= 1),
    CONSTRAINT ck_tips_status CHECK (status IN ('PENDING','WON','LOST','VOID','PENDING_MANUAL'))
);
CREATE INDEX ix_tips_feed   ON tips (community_id, status, published_at DESC);
CREATE INDEX ix_tips_author ON tips (author_id);
CREATE INDEX ix_tips_import ON tips (import_id);

CREATE TABLE tip_selections (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tip_id            BIGINT       NOT NULL REFERENCES tips(id) ON DELETE CASCADE,
    -- NULL permitido: uma tip pode ser publicada com o jogo por associar
    -- quando o fornecedor não tem o jogo dessa liga (secção 10 da spec).
    fixture_id        BIGINT       REFERENCES fixtures(id),
    market            VARCHAR(20)  NOT NULL,
    selection         VARCHAR(20)  NOT NULL,
    line              NUMERIC(4,2),
    odds              NUMERIC(6,3) NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    settlement_source VARCHAR(10),
    settled_by        BIGINT       REFERENCES users(id),
    settled_at        TIMESTAMPTZ,
    version           BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_selection_market CHECK (market IN ('MATCH_RESULT','DOUBLE_CHANCE','OVER_UNDER','BTTS','HANDICAP')),
    CONSTRAINT ck_selection_status CHECK (status IN ('PENDING','WON','LOST','VOID','PENDING_MANUAL')),
    CONSTRAINT ck_selection_source CHECK (settlement_source IS NULL OR settlement_source IN ('AUTO','MANUAL')),
    CONSTRAINT ck_selection_odds   CHECK (odds >= 1)
);
CREATE INDEX ix_selections_fixture_status ON tip_selections (fixture_id, status);
CREATE INDEX ix_selections_tip            ON tip_selections (tip_id);

CREATE TABLE chat_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_id BIGINT        NOT NULL REFERENCES communities(id),
    author_id    BIGINT        NOT NULL REFERENCES users(id),
    content      VARCHAR(2000) NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    deleted_by   BIGINT        REFERENCES users(id)
);
CREATE INDEX ix_chat_history ON chat_messages (community_id, created_at DESC);

CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES users(id),
    type         VARCHAR(40) NOT NULL,
    community_id BIGINT      REFERENCES communities(id),
    tip_id       BIGINT      REFERENCES tips(id),
    payload      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    read_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_notifications_inbox   ON notifications (user_id, read_at, created_at DESC);
CREATE INDEX ix_notifications_created ON notifications (created_at);

CREATE TABLE admin_audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    BIGINT      NOT NULL REFERENCES users(id),
    action      VARCHAR(60) NOT NULL,
    target_type VARCHAR(40) NOT NULL,
    target_id   BIGINT      NOT NULL,
    note        VARCHAR(1000),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_admin ON admin_audit_logs (admin_id, created_at DESC);
