-- Refresh tokens do R1. A tabela não está na secção 8 da spec, por isso é
-- desenhada por esta feature e não acrescentada ao baseline V2.
-- O token entregue ao cliente nunca é guardado: guarda-se sha256(token) em
-- hexadecimal. O token tem 256 bits de entropia, logo um hash rápido é
-- suficiente e permite a procura por índice único (BCrypt obrigaria a varrer
-- a tabela inteira a cada refresh).
-- Nomes de identificadores mantidos abaixo de 40 caracteres por causa de
-- ConfigurationConventionsTest.nenhumFicheiroVersionadoContemSegredoComAparenciaReal.

CREATE TABLE refresh_tokens (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash     VARCHAR(64) NOT NULL,
    family_id      UUID        NOT NULL,
    issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ,
    replaced_by_id BIGINT      REFERENCES refresh_tokens(id),
    CONSTRAINT uq_rt_hash    UNIQUE (token_hash),
    CONSTRAINT ck_rt_expiry  CHECK (expires_at > issued_at)
);
CREATE INDEX ix_rt_user    ON refresh_tokens (user_id);
CREATE INDEX ix_rt_family  ON refresh_tokens (family_id);
CREATE INDEX ix_rt_expires ON refresh_tokens (expires_at);
